version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: web3d_user
      POSTGRES_PASSWORD: secure_password_change_me
      POSTGRES_DB: web3d_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U web3d_user -d web3d_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://web3d_user:secure_password_change_me@db:5432/web3d_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./static:/app/static
      - ./uploads:/app/uploads

volumes:
  postgres_data: